version: '3'
services:
  db:
    image: postgres:12.8
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pikud-darom
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: