version: '3'
services:
  db:
    image: postgres:12.8
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pikud-darom
    volumes:
      - db:/var/lib/postgresql/data
      
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
volumes:
  db: